# Generated by Django 3.2.4 on 2021-06-25 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls_api', '0002_auto_20210625_0513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='downvote_count',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='upvote_count',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='dislike_count',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='like_count',
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CommentVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.BooleanField(blank=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls_api.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnswerVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.BooleanField(blank=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls_api.answer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='user_votes',
            field=models.ManyToManyField(related_name='user_votes', through='polls_api.AnswerVote', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='user_choices',
            field=models.ManyToManyField(related_name='user_choices', through='polls_api.CommentVote', to=settings.AUTH_USER_MODEL),
        ),
    ]
